CREATE TABLE IF NOT EXISTS `users`(
`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
`full_name` VARCHAR(100) NOT NULL,
`password` VARCHAR(255) NOT NULL,
`role` VARCHAR(20) NOT NULL,
`email` VARCHAR(36) NOT NULL,
`phone` VARCHAR(15) NOT NULL,
`created_at` DATETIME NOT NULL,
`updated_at` DATETIME NOT NULL
);