CREATE TABLE IF NOT EXISTS posts(
    id integer NOT NULL PRIMARY KEY generated by default as identity,
    title varchar(100) NOT NULL,
    content TEXT NOT NULL,
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL
);
