CREATE TABLE IF NOT EXISTS `orders`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `user_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
    `order_no` VARCHAR(30) NOT NULL,
    `is_payment` TINYINT NOT NULL DEFAULT 0,
    `total` DECIMAL(19,2) NOT NULL DEFAULT 0,
    `expired_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_order_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `order_details`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `order_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
    `product_id` BIGINT UNSIGNED NOT NULL,
    `qty` INT NOT NULL DEFAULT 0,
    `total` DECIMAL(19,2) NOT NULL DEFAULT 0,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_order_detail_order_id FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_order_detail_product_id FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);