// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	context "context"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	models "test-asset-fendr/src/models"
)

// PostRepositoryInterface is an autogenerated mock type for the PostRepositoryInterface type
type PostRepositoryInterface struct {
	mock.Mock
}

// Begin provides a mock function with given fields: ctx
func (_m *PostRepositoryInterface) Begin(ctx context.Context) *gorm.DB {
	ret := _m.Called(ctx)

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func(context.Context) *gorm.DB); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

// Commit provides a mock function with given fields:
func (_m *PostRepositoryInterface) Commit() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: data
func (_m *PostRepositoryInterface) Create(data *models.Post) error {
	ret := _m.Called(data)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Post) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteOne provides a mock function with given fields: tx, query, args
func (_m *PostRepositoryInterface) DeleteOne(tx *gorm.DB, query string, args ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, tx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, string, ...interface{}) error); ok {
		r0 = rf(tx, query, args...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Error provides a mock function with given fields:
func (_m *PostRepositoryInterface) Error() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindOne provides a mock function with given fields: ctx, query, args
func (_m *PostRepositoryInterface) FindOne(ctx context.Context, query string, args ...interface{}) (models.Post, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 models.Post
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) models.Post); ok {
		r0 = rf(ctx, query, args...)
	} else {
		r0 = ret.Get(0).(models.Post)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, ...interface{}) error); ok {
		r1 = rf(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindOneWithTag provides a mock function with given fields: ctx, query, args
func (_m *PostRepositoryInterface) FindOneWithTag(ctx context.Context, query string, args ...interface{}) (models.PostWithTag, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 models.PostWithTag
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) models.PostWithTag); ok {
		r0 = rf(ctx, query, args...)
	} else {
		r0 = ret.Get(0).(models.PostWithTag)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, ...interface{}) error); ok {
		r1 = rf(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPosts provides a mock function with given fields: ctx, offset, limit
func (_m *PostRepositoryInterface) GetPosts(ctx context.Context, offset int, limit int) ([]models.PostWithTag, error) {
	ret := _m.Called(ctx, offset, limit)

	var r0 []models.PostWithTag
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []models.PostWithTag); ok {
		r0 = rf(ctx, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.PostWithTag)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Rollback provides a mock function with given fields:
func (_m *PostRepositoryInterface) Rollback() {
	_m.Called()
}

// UpdateOne provides a mock function with given fields: tx, data, updatedField, query, args
func (_m *PostRepositoryInterface) UpdateOne(tx *gorm.DB, data models.Post, updatedField string, query string, args ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, tx, data, updatedField, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, models.Post, string, string, ...interface{}) error); ok {
		r0 = rf(tx, data, updatedField, query, args...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewPostRepositoryInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewPostRepositoryInterface creates a new instance of PostRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPostRepositoryInterface(t mockConstructorTestingTNewPostRepositoryInterface) *PostRepositoryInterface {
	mock := &PostRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
